### ISSUE TITLE
Not an issue but Questions

### ISSUE THREAD

**Issue by skyestudiosDev** [WindSekirun/NaraeAudioRecorder#4]
1. Can I use it in a pure Java project in Android
2. Which output is the smallest in size
3. I like your library cuz of silence detection, so on silence can I like save the audio previously recorded?
4. Can I like add timer? Like maxRecording time?

I saw in your documentation but it's not quite clear

**Comment by WindSekirun** [comment]
1. Although you don't use Kotlin in your codebase, Your project should be Java/Kotlin project. In Studio, execute ```Configure Kotlin in Project```
2. If you can use FFmpeg, mp3 will be smallest. otherwise, it can't be small. (PCM and WAV is lossless format)
3. You can use by provide ```OnSilentDetectedListener``` in ```AudioRecorderConfig``` class with NoiseAudioSource. but OnSlientDetectedListener will be called after silent has disappeared. So it can't be done.
4. timerCountListener in AudioRecordConfig is timer feature. If you don't need ```maxRecordingTime```, Set this value to ```Long.MAX_VALUE```

**Comment by skyestudiosDev** [comment]
I've using your library right now. You did great bro. Just asking, is it possible for me to implement a kind of way that I upload the recording to a server in real-time? That is while recording??
